language: python
cache:
    pip: true
    directories:
    - node_modules
matrix:
    include:
    - python: "3.6"

jobs:
  include:
    - stage: vale
      install:
        - ./ci/install/hugo_server.sh
        - go get github.com/ValeLint/vale
      script:
        - vale --glob='*.{md}' docs

    - stage: scripts
      install:
        - ./ci/install/hugo_server.sh
        - pip install -r ci/requirements.txt
      script:
        - echo "Checking for style guidelines"
        - python -m pytest -n 2

